name: 'Trigger and Wait for Workflow'
description: 'Triggers a workflow and waits for its completion with timeout protection'
inputs:
  workflow-file:
    description: 'The workflow file to trigger (e.g., release-stage-2_build_and_release.yml)'
    required: true
  ref:
    description: 'The git ref to run the workflow on'
    required: true
    default: 'latest'
  github-token:
    description: 'GitHub token for authentication'
    required: true
  timeout-minutes:
    description: 'Maximum wait time in minutes'
    required: false
    default: '30'
  run-name:
    description: 'Unique name of the triggered workflow run'
    required: false
    default: ''
  workflow-fields:
    description: 'Fields to pass to the workflow as key=value pairs (JSON or newline separated)'
    required: false
    default: ''

outputs:
  workflow-conclusion:
    description: 'The conclusion of the triggered workflow'
    value: ${{ steps.wait-completion.outputs.conclusion }}
  run-id:
    description: 'The run ID of the triggered workflow'
    value: ${{ steps.extract-run-id.outputs.run_id }}

runs:
  using: 'composite'
  steps:
    - name: Trigger ${{ inputs.run-name }} Workflow
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "::notice::Triggering ${{ inputs.run-name }} workflow - ${{ inputs.workflow-file }}"
        
        # Parse workflow-fields input and build --field arguments
        FIELD_ARGS=""
        if [[ -n "${{ inputs.workflow-fields }}" ]]; then
          while IFS='=' read -r key value; do
            # Only add if both key and value are non-empty
            if [[ -n "$key" && -n "$value" ]]; then
              FIELD_ARGS+=" --field $key=$value"
            fi
          done <<< "${{ inputs.workflow-fields }}"
        fi

        echo "::notice::Using fields: $FIELD_ARGS"

        gh workflow run "${{ inputs.workflow-file }}" \
          --ref "${{ inputs.ref }}" \
          --field run_name="${{ inputs.run-name }}" \
          $FIELD_ARGS || { 
          echo "::error::Failed to trigger ${{ inputs.workflow-file }} workflow"; 
          exit 1; 
        }
        
        echo "::notice::${{ inputs.run-name }} workflow triggered successfully"

    - name: Find ${{ inputs.run-name }} Workflow Run
      id: find-workflow
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "::group::Waiting for ${{ inputs.run-name }} workflow to appear in run list..."

        # Initialize variables
        WORKFLOW_URL=""
        MAX_RETRIES=12  # Retry for up to 1 minute (12 retries * 5 seconds)
        RETRY_COUNT=0

        # Retry loop
        while [[ -z "$WORKFLOW_URL" || "$WORKFLOW_URL" == "null" ]]; do
          if [[ $RETRY_COUNT -ge $MAX_RETRIES ]]; then
            echo "::error::Could not find triggered ${{ inputs.run-name }} workflow run after 1 minute"
            gh run list --workflow "${{ inputs.workflow-file }}" --event workflow_dispatch --branch "${{ inputs.ref }}" --limit 5 --json url,name
            exit 1
          fi

          # Increment retry count
          RETRY_COUNT=$((RETRY_COUNT + 1))

          # Check for the workflow run
          WORKFLOW_URL=$(gh run list --workflow "${{ inputs.workflow-file }}" \
            --event workflow_dispatch \
            --branch "${{ inputs.ref }}" \
            --limit 10 \
            --json url,name \
            --jq '[.[] | select(.name | contains("${{ inputs.run-name }}"))] | .[].url' | \
            head -n 1)

          if [[ -z "$WORKFLOW_URL" || "$WORKFLOW_URL" == "null" ]]; then
            echo "::notice::Retry $RETRY_COUNT/$MAX_RETRIES: ${{ inputs.run-name }} workflow not found. Retrying in 5 seconds..."
            sleep 5
          fi
        done

        echo "::endgroup::"
        echo "::notice::Found ${{ inputs.run-name }} workflow run: $WORKFLOW_URL"
        echo "workflow_url=$WORKFLOW_URL" >> $GITHUB_OUTPUT

    - name: Extract ${{ inputs.run-name }} Workflow Run ID
      id: extract-run-id
      shell: bash
      run: |
        WORKFLOW_URL="${{ steps.find-workflow.outputs.workflow_url }}"
        
        # Extract run ID from the URL
        if [[ "$WORKFLOW_URL" =~ actions/runs/([0-9]+) ]]; then
          RUN_ID="${BASH_REMATCH[1]}"
          echo "::notice::Extracted run ID: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
        else
          echo "::error::Could not extract run ID from workflow URL: $WORKFLOW_URL"
          exit 1
        fi

    - name: Wait for ${{ inputs.run-name }} Workflow Completion
      id: wait-completion
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        RUN_ID="${{ steps.extract-run-id.outputs.run_id }}"
        echo "::group::Waiting for ${{ inputs.run-name }} workflow (run $RUN_ID) to complete..."
        
        # Set maximum wait time (convert minutes to seconds)
        MAX_WAIT_SECONDS=$(( ${{ inputs.timeout-minutes }} * 60 ))
        START_TIME=$(date +%s)
        
        # Poll the workflow status until it completes
        while true; do
          # Check if we've exceeded the maximum wait time
          CURRENT_TIME=$(date +%s)
          ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
          
          if [[ $ELAPSED_TIME -gt $MAX_WAIT_SECONDS ]]; then
            echo "::error::${{ inputs.run-name }} workflow timed out after ${{ inputs.timeout-minutes }} minutes"
            exit 0
          fi
          
          STATUS=$(gh run view "$RUN_ID" --json status -q '.status')
          
          case "$STATUS" in
            "completed")
              CONCLUSION=$(gh run view "$RUN_ID" --json conclusion -q '.conclusion')
              echo "conclusion=$CONCLUSION" >> $GITHUB_OUTPUT
              if [[ "$CONCLUSION" == "success" ]]; then
                echo "::notice::${{ inputs.run-name }} workflow completed successfully"
                break
              else
                echo "::error::${{ inputs.run-name }} workflow failed with conclusion: $CONCLUSION"
                break
              fi
              ;;
            "in_progress"|"queued"|"requested"|"waiting")
              echo "::notice::${{ inputs.run-name }} workflow status: $STATUS - continuing to wait... (elapsed: ${ELAPSED_TIME}s)"
              sleep 30
              ;;
            *)
              echo "::error::${{ inputs.run-name }} workflow has unexpected status: $STATUS"
              break
              ;;
          esac
        done
        echo "::endgroup::"